// <auto-generated />
using System;
using AegeanLogs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AegeanLogs.Infrastructure.Migrations
{
    [DbContext(typeof(AegeanLogsDbContext))]
    partial class AegeanLogsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset"); 

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("SupplierId");

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PortCallId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("EntityName", "EntityId");

                    b.HasIndex("PortCallId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AuditLogEntries", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ClientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClientCompanies", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnLocode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UnLocode")
                        .IsUnique();

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.PortCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualArrivalTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualDepartureTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AssignedAgentUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Eta")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Etd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentUserId");

                    b.HasIndex("Eta");

                    b.HasIndex("Etd");

                    b.HasIndex("Status");

                    b.HasIndex("VesselId", "Eta");

                    b.HasIndex("PortId", "Status", "Eta");

                    b.ToTable("PortCalls", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.PortCallDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CheckedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("PortCallId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("PortCallId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("PortCallId", "Status");

                    b.ToTable("PortCallDocuments", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CheckedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EvidenceFileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PortCallId")
                        .HasColumnType("int");

                    b.Property<string>("ReadinessImpact")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RequirementLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("Deadline");

                    b.HasIndex("PortCallId");

                    b.HasIndex("ReadinessImpact");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("PortCallId", "Status");

                    b.HasIndex("SupplierId", "Status", "Deadline");

                    b.ToTable("ServiceJobs", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceRequirementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeadlineAnchor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DeadlineOffsetHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PortCallPurpose")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Rationale")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReadinessImpact")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RequirementLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("PortCallPurpose", "ServiceTypeId")
                        .IsUnique();

                    b.ToTable("ServiceRequirementRules", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RequiresCompletionEvidence")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresExternalSupplier")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("ServiceTypes", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ServiceCategory");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Vessels", (string)null);
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ClientCompany", "ClientCompany")
                        .WithMany("Users")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegeanLogs.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Users")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientCompany");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.PortCall", "PortCall")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PortCall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.PortCall", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ApplicationUser", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedAgentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.Port", "Port")
                        .WithMany("PortCalls")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.Vessel", "Vessel")
                        .WithMany("PortCalls")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("Port");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.PortCallDocument", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ApplicationUser", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegeanLogs.Domain.Entities.PortCall", "PortCall")
                        .WithMany("Documents")
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CheckedByUser");

                    b.Navigation("PortCall");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceJob", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ApplicationUser", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegeanLogs.Domain.Entities.PortCall", "PortCall")
                        .WithMany("ServiceJobs")
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceJobs")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegeanLogs.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ServiceJobs")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CheckedByUser");

                    b.Navigation("PortCall");

                    b.Navigation("ServiceType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceRequirementRule", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("RequirementRules")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Vessel", b =>
                {
                    b.HasOne("AegeanLogs.Domain.Entities.ClientCompany", "ClientCompany")
                        .WithMany("Vessels")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ClientCompany", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Port", b =>
                {
                    b.Navigation("PortCalls");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.PortCall", b =>
                {
                    b.Navigation("AuditLogEntries");

                    b.Navigation("Documents");

                    b.Navigation("ServiceJobs");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("RequirementRules");

                    b.Navigation("ServiceJobs");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ServiceJobs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AegeanLogs.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("PortCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
